#!/usr/bin/env bash
echo "== create bucket =="
if [ -z "$1" ]; then
    echo "Usage: need <bucket-name>"
    exit 1
fi

aws s3api create-bucket --bucket "$1" --create-bucket-configuration LocationConstraint=eu-west-3