#!/usr/bin/env bash
echo "== delete bucket =="
if [ -z "$1" ]; then
    echo "Usage: need <bucket-name>"
    exit 1
fi

BUCKET="$1"


echo "Emptying bucket: $BUCKET"

# Simple case: remove all current objects (non-versioned buckets, or current versions)
aws s3 rm "s3://$BUCKET" --recursive 

aws s3api delete-bucket --bucket "$1"