#!/usr/bin/env bash
echo "== Add object to a bucket =="
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: need <bucket-name> <file-path>"
    exit 1
fi 

aws s3api put-object --bucket "$1" --key "$(basename "$2")" --body "$2"

